const COMMISSION_RATE=0.10,ADMIN_EMAIL="admin@maxstore.lk";
const CATS=["Electronics","Fashion","Photo & Camera","Beauty","Jewellery","Home & Living","Sports","Grocery","Shoes","Automotive","Mobiles","Computers","Accessories","Toys & Kids","Books","Health","Pet Supplies","Tools","Other"];
const S={Users:["User ID","Name","Email","Phone","Password","Role","Status","Created At"],Products:["Product ID","Seller ID","Name","Category","Price","Stock","Image","Status","Created At"],Orders:["Order ID","User ID","Amount","Admin Commission","Seller Amount","Payment Method","Delivery Method","District","Address","Status","Created At"],OrderItems:["Order ID","Product ID","Seller ID","Name","Price","Qty"],Reviews:["Review ID","Product ID","User ID","Rating","Comment","Created At"],Categories:["Category ID","Name"],Notifications:["Notification ID","User ID","Title","Message","Read","Created At"],Sellers:["Seller ID","User ID","Store Name","Phone","Status","Created At"],Withdrawals:["Withdrawal ID","Seller ID","Amount","Status","Created At"]};
function setup(){let ss=SpreadsheetApp.getActive();Object.keys(S).forEach(n=>{let sh=ss.getSheetByName(n)||ss.insertSheet(n);if(sh.getLastRow()==0)sh.appendRow(S[n])});let c=sh("Categories");if(c.getLastRow()<2)CATS.forEach((x,i)=>c.appendRow(["CAT-"+(i+1),x]))}
function doGet(){return out({success:true,service:"MAX STORE API",message:"Connected 🚀"})}
function doPost(e){try{setup();let d=JSON.parse(e.postData.contents||"{}");switch(d.action){
case"register":return out(register(d));case"login":return out(login(d));case"products":return out({success:true,products:rows("Products").filter(x=>String(x.Status).toLowerCase()=="approved").map(prod)});
case"allProducts":return out({success:true,products:rows("Products").map(prod)});case"categories":return out({success:true,categories:rows("Categories")});
case"users":return out({success:true,users:rows("Users").map(user)});case"sellers":return out({success:true,sellers:rows("Sellers").map(seller)});case"orders":return out({success:true,orders:rows("Orders").map(order)});case"withdrawals":return out({success:true,withdrawals:rows("Withdrawals").map(withdraw)});
case"addProduct":return out(addProduct(d));case"createOrder":return out(createOrder(d));case"sellerDashboard":return out(sellerDash(d));
case"updateSellerStatus":return out(change("Sellers","Seller ID",d.sellerId,"Status",d.status));case"updateProductStatus":return out(change("Products","Product ID",d.productId,"Status",d.status));case"updateOrderStatus":return out(change("Orders","Order ID",d.orderId,"Status",d.status));case"updateWithdrawalStatus":return out(change("Withdrawals","Withdrawal ID",d.withdrawalId,"Status",d.status));default:return out({success:false,error:"Unknown action"})}}catch(x){return out({success:false,error:String(x.message||x)})}}
function register(d){let email=String(d.email||"").trim().toLowerCase();if(!email||!d.password||!d.name)throw Error("Name, email and password required");if(rows("Users").some(x=>String(x.Email).toLowerCase()==email))throw Error("Email already registered");let role=["buyer","seller","both"].includes(String(d.role))?d.role:"buyer",id=uid("USR");append("Users",{"User ID":id,Name:d.name,Email:email,Phone:d.phone||"",Password:hash(d.password),Role:role,Status:"active","Created At":new Date()});if(role=="seller"||role=="both")append("Sellers",{"Seller ID":uid("SEL"),"User ID":id,"Store Name":d.storeName||d.name,Phone:d.phone||"",Status:"Pending","Created At":new Date()});return{success:true,user:{userId:id,name:d.name,email,role}}}
function login(d){let email=String(d.email||"").trim().toLowerCase(),u=rows("Users").find(x=>String(x.Email).toLowerCase()==email&&String(x.Password)==hash(d.password||""));if(!u)throw Error("Invalid email or password");if(String(u.Status).toLowerCase()=="blocked")throw Error("Account blocked");let role=email==ADMIN_EMAIL?"admin":String(u.Role||"buyer");if(d.loginRole=="seller"&&!["seller","both","admin"].includes(role))throw Error("Not a seller account");if(d.loginRole=="buyer"&&role=="seller")throw Error("Choose Seller login");return{success:true,user:{userId:u["User ID"],name:u.Name,email:u.Email,role,status:u.Status}}}
function addProduct(d){if(!d.sellerId||!d.name||Number(d.price)<=0)throw Error("Invalid product");let id=uid("PRD");append("Products",{"Product ID":id,"Seller ID":d.sellerId,Name:d.name,Category:d.category||"Other",Price:Number(d.price),Stock:Number(d.stock||0),Image:d.image||"",Status:"Pending","Created At":new Date()});return{success:true,productId:id}}
function createOrder(d){if(!d.userId||!d.items||!d.items.length)throw Error("Cart empty");let amount=Number(d.total||0),com=Math.round(amount*COMMISSION_RATE*100)/100,id=uid("ORD");append("Orders",{"Order ID":id,"User ID":d.userId,Amount:amount,"Admin Commission":com,"Seller Amount":amount-com,"Payment Method":d.paymentMethod||"COD","Delivery Method":d.deliveryMethod||"Courier","District":d.district||"","Address":d.address||"",Status:"Pending","Created At":new Date()});d.items.forEach(i=>append("OrderItems",{"Order ID":id,"Product ID":i.productId,"Seller ID":i.sellerId||"","Name":i.name||"","Price":Number(i.price||0),Qty:Number(i.qty||1)}));return{success:true,orderId:id,commission:com,sellerAmount:amount-com}}
function sellerDash(d){let ps=rows("Products").filter(x=>String(x["Seller ID"])==String(d.sellerId)).map(prod),ids=rows("OrderItems").filter(x=>String(x["Seller ID"])==String(d.sellerId)).map(x=>x["Order ID"]),os=rows("Orders").filter(x=>ids.includes(x["Order ID"])).map(order);return{success:true,products:ps,orders:os}}
function change(n,k,v,f,nv){let x=find(n,k,v);if(!x)throw Error("Record not found");x.sh.getRange(x.row,x.h.indexOf(f)+1).setValue(nv);return{success:true}}
function append(n,o){let s=sh(n),h=s.getRange(1,1,1,s.getLastColumn()).getValues()[0];s.appendRow(h.map(k=>o[k]??""))}
function rows(n){let s=sh(n);if(!s||s.getLastRow()<2)return[];let v=s.getDataRange().getValues(),h=v.shift();return v.filter(r=>r.some(x=>x!=="")).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]])))}
function find(n,k,v){let s=sh(n),vls=s.getDataRange().getValues(),h=vls[0],i=h.indexOf(k);for(let r=1;r<vls.length;r++)if(String(vls[r][i])==String(v))return{sh:s,row:r+1,h};return null}
function sh(n){return SpreadsheetApp.getActive().getSheetByName(n)}function uid(p){return p+"-"+Date.now()+"-"+Math.floor(Math.random()*99999)}function hash(s){return Utilities.base64Encode(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(s),Utilities.Charset.UTF_8))}function out(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
function prod(x){return{productId:x["Product ID"],sellerId:x["Seller ID"],name:x.Name,category:x.Category,price:Number(x.Price||0),stock:Number(x.Stock||0),image:x.Image,status:x.Status}}function order(x){return{orderId:x["Order ID"],userId:x["User ID"],amount:Number(x.Amount||0),commission:Number(x["Admin Commission"]||0),sellerAmount:Number(x["Seller Amount"]||0),paymentMethod:x["Payment Method"],deliveryMethod:x["Delivery Method"],district:x.District,address:x.Address,status:x.Status,createdAt:x["Created At"]}}function user(x){return{userId:x["User ID"],name:x.Name,email:x.Email,phone:x.Phone,role:x.Role,status:x.Status,createdAt:x["Created At"]}}function seller(x){return{sellerId:x["Seller ID"],userId:x["User ID"],storeName:x["Store Name"],phone:x.Phone,status:x.Status,createdAt:x["Created At"]}}function withdraw(x){return{withdrawalId:x["Withdrawal ID"],sellerId:x["Seller ID"],amount:Number(x.Amount||0),status:x.Status,createdAt:x["Created At"]}}
