const COMMISSION_RATE=0.10;
const ADMIN_EMAIL='admin@maxstore.lk';
const CATS=['Electronics','Fashion','Photo & Camera','Beauty','Jewellery','Home & Living','Sports','Grocery','Shoes','Automotive','Mobiles','Computers','Accessories','Toys & Kids','Books','Health','Pet Supplies','Tools','Other'];
const S={Users:['User ID','Name','Email','Phone','Password','Role','Status','Created At'],Products:['Product ID','Seller ID','Name','Category','Price','Stock','Image','Status','Created At'],Orders:['Order ID','User ID','Amount','Admin Commission','Seller Amount','Payment Method','Delivery Method','District','Address','Status','Created At'],OrderItems:['Order ID','Product ID','Seller ID','Name','Price','Qty'],Reviews:['Review ID','Product ID','User ID','Rating','Comment','Created At'],Categories:['Category ID','Name'],Notifications:['Notification ID','User ID','Title','Message','Read','Created At'],Sellers:['Seller ID','User ID','Store Name','Phone','Status','Created At'],Withdrawals:['Withdrawal ID','Seller ID','Amount','Status','Created At']};
function setup(){const ss=SpreadsheetApp.getActiveSpreadsheet();Object.keys(S).forEach(n=>{let sh=ss.getSheetByName(n)||ss.insertSheet(n);if(sh.getLastRow()===0)sh.appendRow(S[n])});const c=ss.getSheetByName('Categories');if(c.getLastRow()<2)CATS.forEach((x,i)=>c.appendRow(['CAT-'+(i+1),x]));ensureAdmin()}
function ensureAdmin(){if(!rows('Users').some(x=>String(x.Email).toLowerCase()===ADMIN_EMAIL))append('Users',{'User ID':'USR-ADMIN',Name:'MAX STORE OWNER',Email:ADMIN_EMAIL,Phone:'',Password:hash('MaxStore@123'),Role:'admin',Status:'active','Created At':new Date()})}
function doGet(){setup();return out({success:true,service:'MAX STORE API',message:'Connected 🚀',version:'2.0'})}
function doPost(e){try{setup();const d=JSON.parse((e&&e.postData&&e.postData.contents)||'{}');switch(String(d.action||'')){case'register':return out(register(d));case'login':return out(login(d));case'products':return out({success:true,products:rows('Products').filter(x=>String(x.Status).toLowerCase()==='approved').map(prod)});case'allProducts':return out({success:true,products:rows('Products').map(prod)});case'categories':return out({success:true,categories:rows('Categories')});case'users':return out({success:true,users:rows('Users').map(user)});case'sellers':return out({success:true,sellers:rows('Sellers').map(seller)});case'orders':return out({success:true,orders:rows('Orders').map(order)});case'withdrawals':return out({success:true,withdrawals:rows('Withdrawals').map(withdraw)});case'addProduct':return out(addProduct(d));case'createOrder':return out(createOrder(d));case'sellerDashboard':return out(sellerDash(d));case'updateSellerStatus':return out(change('Sellers','Seller ID',d.sellerId,'Status',d.status));case'updateProductStatus':return out(change('Products','Product ID',d.productId,'Status',d.status));case'updateOrderStatus':return out(change('Orders','Order ID',d.orderId,'Status',d.status));case'updateWithdrawalStatus':return out(change('Withdrawals','Withdrawal ID',d.withdrawalId,'Status',d.status));default:return out({success:false,error:'Unknown action: '+d.action})}}catch(x){return out({success:false,error:String(x.message||x)})}}
function register(d){const email=String(d.email||'').trim().toLowerCase(),password=String(d.password||''),name=String(d.name||'').trim();if(!name||!email||password.length<6)throw Error('Name, valid email and password (6+ characters) required');if(rows('Users').some(x=>String(x.Email).toLowerCase()===email))throw Error('Email already registered');const role=['buyer','seller','both'].includes(String(d.role))?String(d.role):'buyer',id=uid('USR');append('Users',{'User ID':id,Name:name,Email:email,Phone:d.phone||'',Password:hash(password),Role:role,Status:'active','Created At':new Date()});let sellerId='';if(role==='seller'||role==='both'){sellerId=uid('SEL');append('Sellers',{'Seller ID':sellerId,'User ID':id,'Store Name':String(d.storeName||name),Phone:d.phone||'',Status:'Pending','Created At':new Date()})}return{success:true,user:{userId:id,name,email,role,sellerId}}}
function login(d){const email=String(d.email||'').trim().toLowerCase(),u=rows('Users').find(x=>String(x.Email).toLowerCase()===email&&String(x.Password)===hash(String(d.password||'')));if(!u)throw Error('Invalid email or password');if(String(u.Status).toLowerCase()==='blocked')throw Error('Account blocked');const role=email===ADMIN_EMAIL?'admin':String(u.Role||'buyer').toLowerCase();let sellerId='';if(role==='seller'||role==='both'){const s=rows('Sellers').find(x=>String(x['User ID'])===String(u['User ID']));sellerId=s?s['Seller ID']:''}return{success:true,user:{userId:u['User ID'],name:u.Name,email:u.Email,role,status:u.Status,sellerId}}}
function addProduct(d){if(!d.sellerId||!d.name||Number(d.price)<=0)throw Error('Valid seller, name and price required');const id=uid('PRD');append('Products',{'Product ID':id,'Seller ID':d.sellerId,Name:String(d.name).trim(),Category:d.category||'Other',Price:Number(d.price),Stock:Number(d.stock||0),Image:d.image||'',Status:'Pending','Created At':new Date()});return{success:true,productId:id}}
function createOrder(d){if(!d.userId||!Array.isArray(d.items)||!d.items.length)throw Error('Cart empty');const amount=Math.round(Number(d.total||0)*100)/100;if(amount<=0)throw Error('Invalid order amount');const com=Math.round(amount*COMMISSION_RATE*100)/100,id=uid('ORD');append('Orders',{'Order ID':id,'User ID':d.userId,Amount:amount,'Admin Commission':com,'Seller Amount':amount-com,'Payment Method':d.paymentMethod||'COD','Delivery Method':d.deliveryMethod||'Courier',District:d.district||'',Address:d.address||'',Status:'Pending','Created At':new Date()});d.items.forEach(i=>append('OrderItems',{'Order ID':id,'Product ID':i.productId,'Seller ID':i.sellerId||'','Name':i.name||'',Price:Number(i.price||0),Qty:Number(i.qty||1)}));return{success:true,orderId:id,commission:com,sellerAmount:amount-com}}
function sellerDash(d){const sid=String(d.sellerId||'');if(!sid)throw Error('Seller ID required');const ps=rows('Products').filter(x=>String(x['Seller ID'])===sid).map(prod),ids=rows('OrderItems').filter(x=>String(x['Seller ID'])===sid).map(x=>String(x['Order ID'])),os=rows('Orders').filter(x=>ids.includes(String(x['Order ID']))).map(order);return{success:true,products:ps,orders:os}}
function change(n,k,v,f,nv){const x=find(n,k,v);if(!x)throw Error('Record not found');x.sh.getRange(x.row,x.h.indexOf(f)+1).setValue(nv);return{success:true}}
function append(n,o){const s=sh(n),h=S[n];s.appendRow(h.map(k=>o[k]??''))}
function rows(n){const s=sh(n);if(!s||s.getLastRow()<2)return[];const v=s.getDataRange().getValues(),h=v.shift();return v.filter(r=>r.some(x=>x!=='')).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]])))}
function find(n,k,v){const s=sh(n),vls=s.getDataRange().getValues(),h=vls[0],i=h.indexOf(k);for(let r=1;r<vls.length;r++)if(String(vls[r][i])===String(v))return{sh:s,row:r+1,h};return null}
function sh(n){return SpreadsheetApp.getActiveSpreadsheet().getSheetByName(n)}function uid(p){return p+'-'+Date.now()+'-'+Math.floor(Math.random()*99999)}function hash(s){return Utilities.base64Encode(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(s),Utilities.Charset.UTF_8))}function out(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
function prod(x){return{productId:x['Product ID'],sellerId:x['Seller ID'],name:x.Name,category:x.Category,price:Number(x.Price||0),stock:Number(x.Stock||0),image:x.Image,status:x.Status}}function order(x){return{orderId:x['Order ID'],userId:x['User ID'],amount:Number(x.Amount||0),commission:Number(x['Admin Commission']||0),sellerAmount:Number(x['Seller Amount']||0),paymentMethod:x['Payment Method'],deliveryMethod:x['Delivery Method'],district:x.District,address:x.Address,status:x.Status,createdAt:x['Created At']}}function user(x){return{userId:x['User ID'],name:x.Name,email:x.Email,phone:x.Phone,role:x.Role,status:x.Status,createdAt:x['Created At']}}function seller(x){return{sellerId:x['Seller ID'],userId:x['User ID'],storeName:x['Store Name'],phone:x.Phone,status:x.Status,createdAt:x['Created At']}}function withdraw(x){return{withdrawalId:x['Withdrawal ID'],sellerId:x['Seller ID'],amount:Number(x.Amount||0),status:x.Status,createdAt:x['Created At']}}
